import pandas as pd
from io import StringIO


def process_csv_file(file_path):
    """_summary_ Had to create this file because the closure_XXXX.csv files are in a strange format that made it diffcult to create the plots

    Args:
        file_path (csv file): takes in a closure csv file generated by Tash
        
    """
    with open(file_path, 'r') as f:
        content = f.read()

    original_lines = []
    closure_lines = []

    for line in content.split('\n'):
        if not line.strip():
            continue
        if line.startswith('ORIGINAL'):
            original_lines.append(line.split(':', 1)[1])
        elif line.startswith('WITH CLOSURE'):
            closure_lines.append(line.split(':', 1)[1])

    original_df = pd.read_csv(StringIO('\n'.join(original_lines)),
                              names=['StopId', 'StartCoord', 'EndCoord', 'StartTime', 'OriginalTime'])
    closure_df = pd.read_csv(StringIO('\n'.join(closure_lines)),
                             names=['StopId', 'StartCoord', 'EndCoord', 'StartTime', 'ClosureTime'])

    merged_df = original_df.merge(closure_df, on=['StopId', 'StartTime'], suffixes=('', '_closure'))

    cleaned_df = merged_df[['StopId', 'StartTime', 'OriginalTime', 'ClosureTime']]

    return cleaned_df


def process_multiple_files(file_list):
    dfs = []
    for file_path in file_list:
        try:
            df = process_csv_file(file_path)
            dfs.append(df)
        except Exception as e:
            print(f"Error processing file {file_path}: {str(e)}")

    if not dfs:
        return pd.DataFrame()

    return pd.concat(dfs, ignore_index=True)
